### ISSUE TITLE
Balance of token sale contract

### ISSUE THREAD

**Issue by ryanfalzon** [dappuniversity/token_sale#29]
Hi,

In the smart contract tests we commission 75% of the tokens to the sale smart contract. however this is not done when we deploy contracts to use fo the front-end. This gives an error as when I try to buy some tokens, the balance of the contract instantiating the transfer function is empty. Can you please point me to what I am missing?

Thanks :)

**Comment by olekashiwa** [comment]
Hi, 
I am planning to buy some tokens, so I had no experience yet.

**Comment by Madeindreams** [comment]
@ryanfalzon 

This is to be expected because the token sale contract doesn't have any tokens yet. The initial transfer to the contract is made with truffle console. However, since the contract has an address it would probably be possible, once fully deployed on the main network with a valid and official address, to send some tokens back to the contract, but the app.js file is using predetermined variable to set the amount of available tokens to be purchased. So this part of the app would need to be updated to get the available tokens from the contract address balance in order to keep track of the available token for sale by the contract. This is one of the step i'm planning to add on my version.
